# Generated by Django 5.1.3 on 2025-01-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nontion_sync', '0011_project_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of material or specification')),
                ('direction', models.CharField(choices=[('project', 'Project'), ('general', 'General')], max_length=50, verbose_name='Direction')),
                ('content', models.TextField(verbose_name='Text of specification or material')),
                ('telegram_user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram User ID who provided the material')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_materials', to='nontion_sync.project', verbose_name='Project')),
            ],
        ),
    ]
