# Generated by Django 5.1.3 on 2025-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_assistants', '0002_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255)),
                ('gpt_id', models.CharField(max_length=255)),
            ],
        ),
    ]
