# Generated by Django 5.1.3 on 2025-04-01 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_assistants', '0004_tok_name'),
        ('nontion_sync', '0015_alter_task_person_tg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChanellAndTopik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topikandcanel_name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('topik_id', models.CharField(max_length=255)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Topik', to='nontion_sync.project', verbose_name='Project')),
            ],
        ),
    ]
