# Generated by Django 5.1.3 on 2025-04-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_assistants', '0005_chanellandtopik'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanellandtopik',
            name='project_external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
