# Generated by Django 5.1.3 on 2025-04-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_assistants', '0006_chanellandtopik_project_external_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chanellandtopik',
            table='AI_assistants_chanellandtopik',
        ),
    ]
