# Generated by Django 5.1.3 on 2025-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_assistants', '0007_alter_chanellandtopik_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('original_question', models.TextField()),
                ('original_response', models.TextField()),
                ('corrected_response', models.TextField(blank=True, null=True)),
                ('feedback', models.CharField(choices=[('👍', 'Good'), ('👎', 'Bad')], max_length=10)),
            ],
            options={
                'db_table': 'AI_assistants_fidback',
            },
        ),
    ]
