# Generated by Django 5.1.3 on 2025-04-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_assistants', '0008_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='AI_assistants_feedback',
        ),
    ]
