# Generated by Django 5.1.3 on 2024-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notion_token', models.CharField(max_length=255)),
                ('database_id', models.CharField(max_length=255)),
                ('auth_endpoint', models.URLField()),
                ('data_endpoint', models.URLField()),
                ('api_login', models.CharField(max_length=255)),
                ('api_password', models.CharField(max_length=255)),
            ],
        ),
    ]
