[program:ai_assistant_bot]
command=python /srv/src/smartassist/V3.02/sync_project/AI_assistants/bot.py
directory=/srv/src/smartassist/V3.02/sync_project
autostart=true
autorestart=true
stderr_logfile=/srv/src/smartassist/V3.02/sync_project/logs/ai_assistant_bot.err.log
stdout_logfile=/srv/src/smartassist/V3.02/sync_project/logs/ai_assistant_bot.out.log
environment=PYTHONPATH="/srv/src/smartassist/V3.02/sync_project"