# Generated by Django 5.1.3 on 2025-01-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotionDbConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notion_token', models.CharField(max_length=255)),
                ('database_id_from', models.CharField(max_length=255)),
                ('database_id_to', models.CharField(max_length=255)),
            ],
        ),
    ]
