# Generated by Django 5.1.3 on 2025-02-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotionDbConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notion_token', models.CharField(max_length=255)),
                ('database_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotionOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=50)),
                ('responsible', models.CharField(blank=True, max_length=50, null=True)),
                ('responsible_pf', models.CharField(blank=True, choices=[('Sense', 'Олександр Sense Штефан'), ('Insomnia', 'Юлия Insomnia Кандалинцева'), ('Ernesto', 'Olena Ernesto Ivashyna'), ('Stamford', 'Vadym Stamford Didenko'), ('Vert', 'Сергей Vert Брагаренко'), ('Lunna', 'Анна Lunna Яковуник'), ('Degtaria', 'Yana Degtaria Dehtiarova'), ('Voice', 'Александр Voice Стадник'), ('Seraphina', 'Oksana Seraphina Hrytsakova'), ('Pulse', 'Andrii Pulse Bobanych'), ('Mirage', 'Petro Mirage Pryimak'), ('SATTVA', 'Інна Sattva Лисенко'), ('Demchik', 'Victoria Demchik Demydova')], max_length=50, null=True, verbose_name='Responsible PF')),
                ('service_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Order description')),
                ('business_unit', models.CharField(blank=True, default='Unknown Business Unit', max_length=250, null=True)),
                ('business_projects', models.CharField(blank=True, default='Unknown Business Project', max_length=250, null=True)),
                ('business_project_pf', models.CharField(blank=True, default='Unknown Business Project PF', max_length=250, null=True)),
                ('category', models.CharField(blank=True, default='Unknown Category', max_length=250, null=True)),
                ('url_docs', models.URLField(blank=True, null=True, verbose_name='URL for dox')),
                ('team', models.CharField(blank=True, default='Unknown team', max_length=250, null=True)),
                ('cost_allocation_type', models.CharField(blank=True, max_length=250, null=True)),
                ('cost_allocation', models.CharField(blank=True, max_length=250, null=True)),
                ('service_id', models.CharField(max_length=255)),
                ('business_unit_id', models.IntegerField()),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('hours_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Plan hours or unit')),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('In progress', 'In progress'), ('Done', 'Done')], max_length=50, null=True, verbose_name='Status')),
                ('record_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name project')),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(max_length=255, verbose_name='Project direction')),
                ('progress', models.FloatField(blank=True, null=True, verbose_name='Progress')),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('In progress', 'In progress'), ('Complete', 'Complete')], max_length=50, verbose_name='Status')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start')),
                ('finish_fact', models.DateField(blank=True, null=True, verbose_name='Finish Fact')),
                ('plan_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Plan cost')),
                ('fact_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fact cost')),
                ('project_manager', models.CharField(max_length=255, verbose_name='Project manager')),
                ('record_hash', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Parent name')),
                ('start', models.DateField(verbose_name='Start')),
                ('finish', models.DateField(verbose_name='Finish')),
                ('hours_plan', models.FloatField(verbose_name='Hours plan')),
                ('hours_fact', models.FloatField(blank=True, null=True, verbose_name='Hours fact')),
                ('progress', models.FloatField(default=0, verbose_name='Progress')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='nontion_sync.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Task Name')),
                ('task_id', models.CharField(blank=True, max_length=150, null=True)),
                ('hours_plan', models.FloatField(blank=True, null=True, verbose_name='Hours plan')),
                ('hours_fact', models.FloatField(blank=True, null=True, verbose_name='Hours fact')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Finish')),
                ('person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Person (Executor)')),
                ('reviewer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reviewer')),
                ('status', models.CharField(blank=True, choices=[('Backlog', 'Backlog'), ('To Do', 'To Do'), ('Need fix', 'Need fix'), ('Review', 'Review'), ('In progress', 'In progress'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=50, null=True, verbose_name='Status')),
                ('plan_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Plan cost')),
                ('fact_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fact cost')),
                ('business_unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Business Unit')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nontion_sync.parent', verbose_name='Parent Task')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nontion_sync.project', verbose_name='Project')),
            ],
        ),
    ]
