# Generated by Django 5.1.3 on 2025-02-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='record_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
