# Generated by Django 5.1.3 on 2025-01-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiondbconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
