# Generated by Django 5.1.3 on 2025-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0002_task_record_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
