# Generated by Django 5.1.3 on 2025-01-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0002_notiondbconfig_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=30)),
                ('service_id', models.IntegerField(max_length=25)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finish_date', models.DateField()),
            ],
        ),
    ]
