# Generated by Django 5.1.3 on 2025-01-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0003_notionorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notionorders',
            name='service_id',
            field=models.IntegerField(),
        ),
    ]
