# Generated by Django 5.1.3 on 2025-02-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0003_alter_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
    ]
