# Generated by Django 5.1.3 on 2025-01-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0004_alter_notionorders_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionorders',
            name='business_unit',
            field=models.CharField(default=12, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notionorders',
            name='order_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notionorders',
            name='responsebil',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notionorders',
            name='service_name',
            field=models.CharField(max_length=300),
        ),
    ]
