# Generated by Django 5.1.3 on 2025-02-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0004_remove_task_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='nontion_sync.parent', verbose_name='Parent Task'),
        ),
        migrations.CreateModel(
            name='AIgenTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Task Name')),
                ('task_id', models.CharField(blank=True, max_length=150, null=True)),
                ('hours_plan', models.FloatField(blank=True, null=True, verbose_name='Hours plan')),
                ('person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Person (Executor)')),
                ('status', models.CharField(blank=True, default='Backlog', max_length=50, null=True, verbose_name='Status')),
                ('plan_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Plan cost')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковий номер')),
                ('record_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_subtasks', to='nontion_sync.parent', verbose_name='Parent Task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nontion_sync.project', verbose_name='Проєкт')),
            ],
        ),
    ]
