# Generated by Django 5.1.3 on 2025-02-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0005_alter_task_parent_task_aigentask'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionorders',
            name='order_id_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
