# Generated by Django 5.1.3 on 2025-01-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0005_notionorders_business_unit_notionorders_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notionorders',
            name='responsebil',
        ),
        migrations.AddField(
            model_name='notionorders',
            name='responsible',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
