# Generated by Django 5.1.3 on 2025-02-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0006_notionorders_order_id_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='finish',
            field=models.DateField(blank=True, null=True, verbose_name='Finish'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='hours_plan',
            field=models.FloatField(blank=True, null=True, verbose_name='Hours plan'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='progress',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Progress'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Start'),
        ),
    ]
