# Generated by Django 5.1.3 on 2025-01-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0006_remove_notionorders_responsebil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionorders',
            name='business_unit_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
