# Generated by Django 5.1.3 on 2025-03-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0007_alter_parent_budget_alter_parent_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='telegram_topik_id',
            field=models.PositiveIntegerField(default=0, verbose_name='ID Підгрупи телеграму'),
        ),
    ]
