# Generated by Django 5.1.3 on 2025-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0008_project_telegram_topik_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL for task'),
        ),
    ]
