# Generated by Django 5.1.3 on 2025-01-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0008_notionorders_record_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notiondbconfig',
            old_name='database_id_from',
            new_name='database_id',
        ),
        migrations.RemoveField(
            model_name='notiondbconfig',
            name='database_id_to',
        ),
    ]
