# Generated by Django 5.1.3 on 2025-01-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0009_rename_database_id_from_notiondbconfig_database_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notionorders',
            name='service_id',
            field=models.CharField(max_length=255),
        ),
    ]
