# Generated by Django 5.1.3 on 2025-03-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0010_telegramusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='name_notion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name TG'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='name_tg',
            field=models.CharField(max_length=255, verbose_name='Name TG'),
        ),
    ]
