# Generated by Django 5.1.3 on 2025-01-27 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0010_alter_notionorders_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name project')),
                ('direction', models.CharField(max_length=255, verbose_name='Project direction')),
                ('progress', models.FloatField(default=0, verbose_name='Progress')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], max_length=50, verbose_name='Status')),
                ('start', models.DateField(verbose_name='Start')),
                ('finish_fact', models.DateField(blank=True, null=True, verbose_name='Finish Fact')),
                ('plan_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Plan cost')),
                ('fact_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fact cost')),
                ('project_manager', models.CharField(max_length=255, verbose_name='Project manager')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Parent name')),
                ('start', models.DateField(verbose_name='Start')),
                ('finish', models.DateField(verbose_name='Finish')),
                ('hours_plan', models.FloatField(verbose_name='Hours plan')),
                ('hours_fact', models.FloatField(blank=True, null=True, verbose_name='Hours fact')),
                ('progress', models.FloatField(default=0, verbose_name='Progress')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Budget')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='nontion_sync.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Task Name')),
                ('hours_plan', models.FloatField(verbose_name='Hours plan')),
                ('hours_fact', models.FloatField(blank=True, null=True, verbose_name='Hours fact')),
                ('start', models.DateField(verbose_name='Start')),
                ('finish', models.DateField(verbose_name='Finish')),
                ('person', models.CharField(max_length=255, verbose_name='Person (Executor)')),
                ('reviewer', models.CharField(max_length=255, verbose_name='Reviewer')),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('To Do', 'To Do'), ('Need fix', 'Need fix'), ('Review', 'Review'), ('In progress', 'In progress'), ('Canceled', 'Canceled'), ('Completed', 'Completed')], max_length=50, verbose_name='Status')),
                ('plan_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Plan cost')),
                ('fact_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Fact cost')),
                ('business_unit', models.CharField(max_length=255, verbose_name='Business Unit')),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nontion_sync.parent', verbose_name='Parent Task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='nontion_sync.project', verbose_name='Project')),
            ],
        ),
    ]
