# Generated by Django 5.1.3 on 2025-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0012_alter_project_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='plan_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Plan cost'),
        ),
    ]
