# Generated by Django 5.1.3 on 2025-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0012_alter_telegramusers_name_notion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='name_notion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name Notion'),
        ),
    ]
