# Generated by Django 5.1.3 on 2025-01-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0013_alter_project_plan_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
