# Generated by Django 5.1.3 on 2025-03-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0013_alter_telegramusers_name_notion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='person_tg',
            field=models.CharField(blank=True, choices=[('External persons', 'External persons'), ('Stamford', 'dv_vadym'), ('Pulse', 'andrii_pulse_netpeak'), ('Degtaria', 'degtaria'), ('Voice', 'voice_netpeak'), ('Insomnia', 'Julia_kandalintseva'), ('Mirage', 'Petro_Pryimsk')], max_length=150, null=True, verbose_name='Person_tg'),
        ),
    ]
