# Generated by Django 5.1.3 on 2025-01-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0014_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='record_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
