# Generated by Django 5.1.3 on 2025-03-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0014_task_person_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='person_tg',
            field=models.CharField(blank=True, choices=[('External persons', 'External persons'), ('Stamford', 'dv_vadym'), ('Pulse', 'andrii_pulse_netpeak'), ('Degtaria', 'degtaria'), ('Voice', 'voice_netpeak'), ('Insomnia', 'Julia_kandalintseva'), ('Mirage', 'Petro_Pryimsk'), ('Unknown Person', 'Unknown Person')], max_length=150, null=True, verbose_name='Person_tg'),
        ),
    ]
