# Generated by Django 5.1.3 on 2025-01-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0015_project_record_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.FloatField(blank=True, null=True, verbose_name='Progress'),
        ),
    ]
