# Generated by Django 5.1.3 on 2025-02-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0018_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notionorders',
            name='business_unit',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
