# Generated by Django 5.1.3 on 2025-02-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0019_alter_notionorders_business_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notionorders',
            name='business_unit',
            field=models.CharField(blank=True, default='Unknown Business Unit', max_length=250, null=True),
        ),
    ]
