# Generated by Django 5.1.3 on 2025-02-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0020_alter_notionorders_business_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionorders',
            name='cost_allocation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notionorders',
            name='cost_allocation_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notionorders',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order direction'),
        ),
        migrations.AddField(
            model_name='notionorders',
            name='hours_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Plan cost'),
        ),
        migrations.AddField(
            model_name='notionorders',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('In progress', 'In progress'), ('Done', 'Done')], max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='notionorders',
            name='team',
            field=models.CharField(blank=True, default='Unknown team', max_length=250, null=True),
        ),
    ]
