# Generated by Django 5.1.3 on 2025-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0021_notionorders_cost_allocation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notionorders',
            name='direction',
        ),
        migrations.AddField(
            model_name='notionorders',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Order description'),
        ),
    ]
