# Generated by Django 5.1.3 on 2025-02-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nontion_sync', '0022_remove_notionorders_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionorders',
            name='business_projects',
            field=models.CharField(blank=True, default='Unknown Business Project', max_length=250, null=True),
        ),
    ]
